Repository OpenIMSDK/community, pull requests merged in 2023-05, with the labels that each got.

#3 test: backup cra file
  CLA.md
Labels: test

#4 fix: template styles
  0000-template.md
Labels: bug, documentation

#5 fix: template styles
  RFC/0001-server-suggest-flutter.md
Labels: documentation, good first issue

#6 docs: add Google Docs templates
  CONTRIBUTING.md
Labels: documentation

#7 fix: template styles
  .github/OWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  0000-template.md
  BRANDING.md
  guide/owners.md
Labels: documentation, feat

#8 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation

#9 Feat/issue super
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/slack.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, feat

#11 feat: issue template supports feature requests
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: documentation, good first issue, feat

#12 feat: issue template supports feature requests
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/settings.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, feat

#16 delete .github
  roadmaps/2023.md
Labels: documentation, feature

#20 docs : Create CONTRIBUTING_zh.md
  CONTRIBUTING_zh.md
Labels: documentation, good first issue
